# build React app
FROM node:18-alpine AS build

# Create app directory
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the source code
COPY . .

ARG REACT_APP_API_URL
ENV REACT_APP_API_URL=$REACT_APP_API_URL

# Build for production
RUN npm run build

# serve with a simple static server
FROM node:18-alpine

WORKDIR /app

# Install a lightweight static file server
RUN npm install -g serve

# Copy build output from previous stage
COPY --from=build /app/build ./build

# Expose port 3000 inside container
EXPOSE 3000

# Run the static server
CMD ["serve", "-s", "build", "-l", "3000"]
